### ISSUE TITLE
Sample rate issue during playback from Audio buffer

### ISSUE THREAD

**Issue by glu** [libcala/wavy#24] opened 2021-01-10 20:51 UTC
**Describe the bug**
First of all, thanks for your great work on this library! While writing a program for reading an mp3 using `rodio` and playing it back using `wavy`, I noticed that samples seem to be consumed from `Audio` buffers with `.drain()` at a rate that does not correspond to the rate specified in the `Audio` buffer. See the program below for an example. This results in the audio being quite distorted and slowed down / stuttering in my case. I tried manually feeding chunks to the `SpeakersSink` at the appropriate sample rate. This does seem to fix the distorted sound issue (minus some audible clicks inbetween feeding the chunks, which are expected), but then the `speakers.play().await` call freezes randomly after a few seconds in the song. Perhaps I am using the API in a wrong way?

**To Reproduce**
Here is the example code to measure the approximate samples per second consumed from the buffer:
```rust
use fon::{stereo::Stereo32, Sink, Audio};
use pasts::{exec, wait};
use wavy::{Speakers, SpeakersSink};
use rodio::decoder::Decoder;
use std::io::BufReader;
use std::time::Instant;

enum Event<'a> {
    Play(SpeakersSink<'a, Stereo32>)
}

struct State {
    buffer: Audio<Stereo32>,
    last_time: Instant,
    last_len: usize
}

impl State {
    fn event(&mut self, event: Event<'_>) {
        match event {
            Event::Play(mut speakers) => { 
                speakers.stream(self.buffer.drain());
                let current_time = Instant::now();
                let current_len = self.buffer.len();
                let diff_time = current_time - self.last_time;
                let diff_len = self.last_len - current_len;
                //println!("Estimated samples per instant: {:?}/{:?}", diff_len, diff_time);
                let diff_time_ns = diff_time.subsec_nanos() as f64;
                let sps = (diff_len as f64) / diff_time_ns * 1000000000.0;
                println!("Estimated samples per second: {:?}", sps);

                self.last_time = current_time;
                self.last_len = current_len;
            }
        }
    }
}

fn main() {
    let mut speakers = Speakers::default();
    let example_decoder = Decoder::new(BufReader::new(std::fs::File::open("/path/to/song.mp3").unwrap())).unwrap();
    let vector: Vec<f32> = example_decoder.map(|x| (x as f32) / 32768.0).collect();
    let buffer = Audio::<Stereo32>::with_f32_buffer(48_000, vector);
    let mut state = State { last_len: buffer.len(), buffer: buffer, last_time: Instant::now() };

    exec!(state.event(wait! {
        Event::Play(speakers.play().await),
    }))
}
```

**Expected behavior**
I would expect samples to be consumed at 48,000 samples per second as specified in the `Audio` buffer (and on my soundcard), but they are consumed at about ~20,000 samples per second on my system.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux 5.9.16

**Additional context**
The examples from the `examples` folder work fine (e.g. when recording using `Microphone` and immediately playing back like in `monitor.rs`, this issue does not occur).

Any idea what might be the cause?

**Comment by AldaronLau** [comment] 2021-01-10 23:51
@glu Thank you for the bug(?) report!  I'll look into this, and get back to you as soon as I can.  At a glance it looks like you're using the API correctly.  I'll have to read the rodio api docs to have more information on this.  `speakers.play().await` probably shouldn't freezing either, so I'll look into that as well.

**Comment by glu** [comment] 2021-01-11 05:54
Great, thank you! I will try to help out and see if I can find the issue.

**Comment by AldaronLau** [comment] 2021-01-11 15:14
@glu It looks like there are 3 different problems going on here:

1. speakers.play().await call freezes randomly

This is because of a bug I just discovered in the **smelling_salts** crate, where the speaker becomes ready before the waker is registered.

2. Distortion

Not 100% sure of the cause of this yet.

3. Samples consumed at the wrong rate.

I believe this may be an issue with your code making some assumptions about the sample rate returned from rodio.  Try with the following modifications:

```rust
use fon::stereo::{Stereo16, Stereo32};
use fon::{Sink, Audio};
use pasts::{exec, wait};
use wavy::{Speakers, SpeakersSink};
use rodio::decoder::Decoder;
use rodio::source::Source;
use std::io::BufReader;
use std::time::Instant;

enum Event<'a> {
    Play(SpeakersSink<'a, Stereo32>)
}

struct State {
    buffer: Audio<Stereo16>,
    last_time: Instant,
    last_len: usize
}

impl State {
    fn event(&mut self, event: Event<'_>) {
        match event {
            Event::Play(mut speakers) => {
                println!("Playing…");
                speakers.stream(self.buffer.drain());
                let current_time = Instant::now();
                let current_len = self.buffer.len();
                let diff_time = current_time - self.last_time;
                let diff_len = self.last_len - current_len;
                //println!("Estimated samples per instant: {:?}/{:?}", diff_len, diff_time);
                let diff_time_ns = diff_time.subsec_nanos() as f64;
                let sps = (diff_len as f64) / diff_time_ns * 1000000000.0;
                println!("Estimated samples per second: {:?}", sps);

                self.last_time = current_time;
                self.last_len = current_len;
            }
        }
    }
}

fn main() {
    let mut speakers = Speakers::default();

    println!("Reading file…");

    let example_decoder = Decoder::new(BufReader::new(
        std::fs::File::open("/path/to/audio.mp3").unwrap()
    )).unwrap();

    // Read from rodio decoder into fon audio buffer.
    let buffer = Audio::<Stereo16>::with_i16_buffer(
        example_decoder.sample_rate(),
        example_decoder.collect::<Vec<i16>>(),
    );

    println!("Starting…");

    let mut state = State { last_len: buffer.len(), buffer: buffer, last_time: Instant::now() };

    exec!(state.event(wait! {
        Event::Play(speakers.play().await),
    }))
}
```

**Comment by glu** [comment] 2021-01-11 19:04
Hi @AldaronLau, thanks for the quick reply. I'm glad that you were able to find the cause of the freezing issue; that was fast :).

As for the sample rate: my audio file was sampled at 48 kHz and this corresponds to the `decoder.sample_rate()` reported by `rodio`. Also, if the sample rate were incorrect, I think this would be audible as a lower / higher pitch rather than stuttering / a distorted sound. 

That said, I have found something interesting that might bring us closer to the solution: I noticed that the sample rate started to increase the longer I listened to the song, while the distortion decreased. This made me suspect that it has something to do with the conversion to `Vec` here: https://docs.rs/fon/0.4.0/src/fon/audio.rs.html?search=#240. Perhaps this operation is taking too long, allowing only a handful of samples to be consumed from the buffer, especially in the beginning.

To test my hypothesis, I took a subset from the song, and ... it worked! If you add for example a `.take(400000)` before the `collect()` in my example above, (a few seconds from) the song will sound almost perfect. I think there is still a very faint distorted effect going on, but maybe it would be possible to remove that as well by splitting the buffer into even smaller chunks before feeding to `.drain()`.

**Comment by AldaronLau** [comment] 2021-01-11 22:19
@glu Thanks for the extra details.  Interestingly, though, your `collect()` happens before the main executor loop - so I think you're on to something, but I also think there might be something else going on.  With my testing, the audio was played back at the correct sample rate with my above code and didn't change over time (though severely distorted).  This might just be that my hardware is faster?  Or maybe double check your mp3 is stereo?  Otherwise I don't know how to reproduce the problem.  Optimizing `drain()` is definitely something that could be worked on.

I'm also not 100% sure, but guessing that rodio is returning interleaved audio frames that aren't reordered in any way, which would be correct - but, I couldn't find anything in the documentation about it.  Otherwise, samples might be taken from later in the song and played earlier, causing distortion, but that seems unlikely.

**Comment by glu** [comment] 2021-01-11 22:59
Interesting, yes could be that it is something hardware related. Tomorrow
evening I could check on another device. And my mp3 is indeed stereo.

In any case, for my use case it is not really a problem to chunk the
decoded data before feeding it to the SpeakersSink, and with the fixed
freezing issue I think it will work well, so feel free to close this issue
if you want. Many thanks for your help and your time! Much appreciated.

**Comment by AldaronLau** [comment] 2021-01-11 23:02
@glu No problem!  I plan to at least leave the issue open until I fix the freezing issue (working on it right now), as well as the distortion issue.

**Comment by AldaronLau** [comment] 2021-01-12 05:38
@glu Sorry, you were right and I was wrong (I stupidly didn't know the tempo of the song I was playing).  I think I know how to fix this issue now, but it'll take a bit of code refactoring.  I recorded the audio output in audacity, which showed there was silence inserted randomly between samples.  Oddly enough, the played back sound from audacity sounded without distortion (I think the alsa driver just flakes out when it's not getting samples quickly enough).  I'll try to get a patched version of **smelling_salts** and **fon** released this weekend that should fix everything.  I currently plan to make `Audio` wrap a `VecDeque` instead of a `Box<[]>` so that it won't matter what the buffer size is, it will take the same amount of time to call `drain()`.

**Comment by glu** [comment] 2021-01-12 07:42
No worries! Nice idea, thanks for your work on this. Let me know if I can help in any way. I'm quite new to Rust, so I'm learning a lot with this.

**Comment by AldaronLau** [comment] 2021-01-14 03:18
@glu I would offer to mentor on this fix, but unfortunately it's quite complicated, involves some `unsafe` and is kind of a large internal change for the fon crate (I'm not quite sure what all the details are going to be yet).  I'm still in the process of figuring out how to make my crates more accessible for contributions; I know a lot of crates have "good first issue" labels on some issues, but it's difficult for me to either not fix it right away or even find simpler issues.  Thank you again for your interest, opening the issue, and discovering what's going on with fon and the `drain()` method.

**Comment by glu** [comment] 2021-01-14 19:47
No worries, thanks for the update!

**Comment by AldaronLau** [comment] 2021-01-17 17:56
Wavy 0.9 should be fixed!  fon's `Audio` now encapsulates a `VecDeque` and smelling_salts timing is now fixed, so it shouldn't freeze anymore.

**Closed by AldaronLau** 2021-01-17 17:56 UTC
Labels: bug

**Comment by glu** [comment] 2021-01-18 19:29
Great! The sample rate issue seems solved, although there is still some audible distortion that I do not hear with other audio playback libraries (but that is a different issue or perhaps something on my end). One small remark: I got a compile error (`error[E0658]`) with stable Rust, because `make_contiguous` is considered an unstable feature. So users need nightly Rust to compile the current version. I don't know if this was intentional or not. Thanks for your work on this!

**Comment by AldaronLau** [comment] 2021-01-18 22:24
@glu I never use nightly.  If you check [the documentation](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.make_contiguous), it says as long as you're running 1.48.0 you can use it.  I have the newest stable installed which is 1.49.0, no need for nightly.  At the current moment all of my crates target newest stable, maybe at some point I'll consider officially supporting a minimum version, but development is a lot easier for me without that restriction.

The audible distortion likely has something to do with [this issue](https://github.com/AldaronLau/fon/issues/4) that I found while working on fixing this bug.  Otherwise, it could be that samples still aren't generated fast enough, or your conversion code is introducing distortion somehow.

**Comment by glu** [comment] 2021-01-19 16:45
Ah, it seems my toolchain was out of date :).
